### ISSUE TITLE
Playstore Sample

### ISSUE THREAD

**Issue by JoaquimLey** [andremion/Theatre#1]
Hello, thanks for the awesome project 👏 

- Would you please consider publishing a sample on the Playstore?

**Comment by andremion** [comment]
For sure! 👌🏻
I am going to do this week. But before that, I need to solve a problem occurring when I use the production endpoint.
Appreciate your support! 😉
Thanks! 👍🏻

**Comment by andremion** [comment]
[https://play.google.com/store/apps/details?id=com.andremion.theatre](https://play.google.com/store/apps/details?id=com.andremion.theatre)
