### ISSUE TITLE
Want to understand it without RXJava

### ISSUE THREAD

**Issue by TheReprator** [andremion/Theatre#22]
In the domain section, Rxjava is the thing which redirects the result from respective data source to corresponding presenter for success or Error

So, I only want to understand how can I do it without RXJava, as.  It will be great if you can provide me sample to do it without RXjava or how didi't worked

**Comment by andremion** [comment]
Here is a good repo to see how it works without any reactive library.
https://github.com/googlesamples/android-architecture/tree/todo-mvp-clean/

Basically you will need to use callbacks back and forth.

As you can see there, the [presenter](https://github.com/googlesamples/android-architecture/blob/todo-mvp-clean/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TasksPresenter.java#L104), [usecase](https://github.com/googlesamples/android-architecture/blob/todo-mvp-clean/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/domain/usecase/GetTasks.java#L53), [repository](https://github.com/googlesamples/android-architecture/blob/todo-mvp-clean/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/data/source/TasksRepository.java#L110), use callbacks with some kind of success and error methods to handle the results.
